Feature/fdp 1128 change inet address
OSGP/open-smart-grid-platform pull request #1040
Opened 2023-07-20 11:56 UTC by LucianoFavoroso

2023-07-21 13:00 UTC, sanderv requested changes

2023-07-21 13:00 UTC, sanderv commented on osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/tasks/BaseTask.java
> +    return lightMeasurementDevice.getGatewayDevice().getNetworkAddress();
Hier geef je de string uit de database, wat ook een hostname kan zijn, moet dus via InetAddress

2023-07-21 13:00 UTC, sanderv commented on osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/valueobjects/CdmaBatchDevice.java
> +      return null;
Graag wel de exception loggen

2023-07-21 13:00 UTC, sanderv commented on osgp/platform/osgp-adapter-domain-publiclighting/src/test/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/services/CdmaBatchTest.java
> +    final CdmaBatchDevice cd1 = new CdmaBatchDevice("cd1", this.loopbackAddress.getHostAddress());
`getHostAddress()` kun je al aanroepen bij de initialisatie van de variabele, dan heb je 'm al klaar voor de hele test.

2023-07-21 13:00 UTC, sanderv commented on osgp/platform/osgp-adapter-ws-admin/src/main/java/org/opensmartgridplatform/adapter/ws/admin/application/services/DeviceManagementService.java
> +        final InetAddress inetAddress = InetAddress.getByName(ipAddress);
Ik zou de param gewoon hernoemen naar `networkAddress` en alle conversie verwijderen. Als de aanroeper een hostname meegeeft, dan slaan we dat op...

2023-07-21 13:00 UTC, sanderv commented on osgp/platform/osgp-adapter-domain-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/domain/da/application/services/RtuDeviceService.java
> +    rtuDeviceEntity.updateRegistrationData(inetAddress.getHostAddress(), RtuDevice.PSD_TYPE);
Hier zou ik `networkAddress` gebruiken en niet vertalen naar een IP adres. De logica om een evt. IP-adres te valideren moet je ook even goed bekijken

2023-07-21 13:01 UTC, sanderv commented
Ik zie twee `DeviceRequest` classes in protocol-adapters:

- org.opensmartgridplatform.adapter.protocol.iec61850.device.DeviceRequest
- org.opensmartgridplatform.adapter.protocol.oslp.elster.device.DeviceRequest

Dat zijn de objecten die gebruikt worden om verbinding te krijgen met devices op het netwerk. Ik zou in de `Builder`s  in die classes InetAddress gebruiken om het IP adres te krijgen.

2023-08-16 14:05 UTC, jasperkamerling approved these changes

2023-08-16 14:19 UTC, sanderv approved these changes

2023-08-29 09:40 UTC, JelleHoffman commented
Retest this please

2023-08-30 11:30 UTC, abolder approved these changes

2023-10-04 06:32 UTC, kroesctrl commented
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/134/

2023-10-11 08:53 UTC, Marcel-Jansen approved these changes
Testen voor SMHE met LTE (statisch ip), GPRS (dynamisch ip) en simulators (DNS) geslaagd.

2023-10-11 11:17 UTC, merged