Feature/smhe 1740 config service test alarm scheduler command executor
OSGP/open-smart-grid-platform pull request #1087
Opened 2023-10-02 07:12 UTC by natasja-n

2023-10-09 06:23 UTC, kroesctrl requested changes

2023-10-09 06:23 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-smr51.json
> +          "value": "EMPTY",
EMPTY zie ik niet in de spec staan

2023-10-09 06:23 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-smr55.json
> +          "value": "EMPTY",
EMPTY staat niet in de specs

2023-10-09 06:23 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-smr55.json
> +          "datatype": "visible-string",
In de spec staat: script

2023-10-23 13:25 UTC, natasja-n commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-smr51.json
> +          "value": "EMPTY",
empty is verwijderd.

2023-10-24 05:42 UTC, natasja-n commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-smr51.json
> +          "value": "EMPTY",
EMPTY is verwijderd.

2023-10-24 05:42 UTC, natasja-n commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-smr55.json
> +          "value": "EMPTY",
EMPTY is verwijderd.

2023-10-24 05:42 UTC, natasja-n commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-smr55.json
> +          "datatype": "visible-string",
script is toegevoegd.

2023-10-24 07:40 UTC, kroesctrl approved these changes

2023-10-24 08:41 UTC, merged