SMHE-1871 Onbekende meter events die niet gemapped kunnen worden onde…
OSGP/open-smart-grid-platform pull request #1179
Opened 2024-02-26 13:14 UTC by natasja-n

…r verzamel event

2024-03-01 10:04 UTC, harrymiddelburgetall requested changes

2024-03-01 10:04 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringbundle/BundledFindEventsSteps.java
> +  @And(
@Then

2024-03-01 10:04 UTC, harrymiddelburgetall commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/EventType.java
> +  UNKNOWN_EVENT_HEADEND(47);
HEADEND reference in core?

2024-03-01 10:04 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/EventService.java
> +    UNKNOWN_EVENT_HEADEND(EventTypeDto.UNKNOWN_EVENT_HEADEND, 0x84A1, null);
Where does this int code come from 0x84A1?

2024-03-01 10:04 UTC, harrymiddelburgetall commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/EventType.java
> +  UNKNOWN_EVENT_HEADEND(47);
HEADEND reference in core?
EventCode 47 also is used for CONFIGURATION_CHANGE?

2024-03-04 07:32 UTC, natasja-n commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringbundle/BundledFindEventsSteps.java
> +  @And(
@And is aangepast naar @Then

2024-03-04 07:32 UTC, natasja-n commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/EventType.java
> +  UNKNOWN_EVENT_HEADEND(47);
klopt, dit is de naam zoals gegeven in de story. Het lijkt me het beste als hij overal hetzelfde heet.

2024-03-04 07:33 UTC, natasja-n commented on osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/EventService.java
> +    UNKNOWN_EVENT_HEADEND(EventTypeDto.UNKNOWN_EVENT_HEADEND, 0x84A1, null);
Deze had ik als nog niet bestaande code toegevoegd. Ik heb er nu 999 van gemaakt, zodat duidelijk is dat hij buiten de bestaande ranges valt.

2024-03-04 07:34 UTC, natasja-n commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/EventType.java
> +  UNKNOWN_EVENT_HEADEND(47);
Deze is ook aangepast naar 999 zoals in de opmerking hierboven.

2024-03-04 08:13 UTC, harrymiddelburgetall approved these changes

2024-03-04 13:15 UTC, merged