feature/connection-exception-on-release-permit-causes-request-retry
OSGP/open-smart-grid-platform pull request #1263
Opened 2024-03-22 14:18 UTC by harrymiddelburgetall

ConnectTimeoutException on a call to release a permit in ThrottlingService cause a runtimeexception leading to retry of a devicerequest although the request was already successfully handled.

2024-03-22 14:46 UTC, stefanermens requested changes

2024-03-22 14:46 UTC, stefanermens commented on osgp/shared/osgp-throttling-client/src/test/java/org/opensmartgridplatform/throttling/ThrottlingClientTest.java
> +    // eq(Integer.class))).thenReturn(Integer.valueOf(1));
Can this code be removed?

2024-03-25 07:17 UTC, kroesctrl approved these changes
Is er ook onderzocht waarom throttling het nu lastig heeft?

2024-03-25 07:54 UTC, stefanermens approved these changes

2024-03-25 08:02 UTC, merged