Decrease message priority before retry
OSGP/open-smart-grid-platform pull request #1268
Opened 2024-03-28 21:04 UTC by jboon

To prevent higher priority retries from blocking lower priority messages like firmware update, this feature enables priority decrease for message that will be retried.

Example properties:

schedule.retry.dlms.decrease_priority.enabled=true
schedule.retry.dlms.decrease_priority.interval=2
schedule.retry.dlms.decrease_priority.value=1
schedule.retry.dlms.decrease_priority.min_priority=0

interval: determines after how many retries a decrementation takes place
value: determines the amount with which the priority is lowered

2024-03-29 14:35 UTC, natasja-n commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/DlmsConnectionMessageProcessor.java
> +      //      messageBuilder.result(ResponseMessageResultType.NOT_OK);
remove comment

2024-03-29 15:03 UTC, kroesctrl requested changes

2024-04-02 06:02 UTC, kroesctrl requested changes

2024-04-02 06:02 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagePriorityHandler.java
> +        && (retryCount > 0 || this.decreaseInterval == 1)
`|| this.decreaseInterval == 1` begrijp ik niet

2024-04-02 07:08 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagePriorityHandler.java
> +        && (retryCount > 0 || this.decreaseInterval == 1)
Als de prio elke (1) keer verlaagd wordt dan moet dat direct de eerste keer ook gebeuren (bij 0 retries), maar anders niet.

2024-04-02 07:14 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/DlmsConnectionMessageProcessor.java
> +      //      messageBuilder.result(ResponseMessageResultType.NOT_OK);
removed, thnx

2024-04-02 07:28 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagePriorityHandler.java
> +        && (retryCount > 0 || this.decreaseInterval == 1)
Ok, als de retry count de eerste keer 0 is, dan heb ik mijn twijfels over deze oplossing.
Want als de decreaseInterval dan 2 is, dan gaat ie pas bij de 3e poging 1 omlaag

2024-04-02 12:39 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagePriorityHandler.java
> +        && (retryCount > 0 || this.decreaseInterval == 1)
Het is nog iets anders. De eerste call doet niet mee in het verhaal. Vanaf de eerste retry wordt bepaald of het algoritme toegepast moet worden.

2024-04-02 13:22 UTC, natasja-n approved these changes

2024-04-02 14:01 UTC, kroesctrl requested changes

2024-04-02 14:01 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagePriorityHandler.java
> +    if (this.decreaseEnabled && (retryCount > 0) && retryCount % this.decreaseInterval == 0) {
Als hij hier nu de eerste keer langs komt, en je wilt dat ie met iedere retry omlaag gaat (this.decreaseInterval == 1), dan komt wordt ie de 2e keer met dezelfde priority verwerkt

2024-04-02 14:04 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagePriorityHandler.java
> +        && (retryCount > 0 || this.decreaseInterval == 1)
Zie nieuw commentaar, ben het er niet mee eens.....

2024-04-02 14:20 UTC, kroesctrl approved these changes

2024-04-02 14:21 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagePriorityHandler.java
> +        && (retryCount > 0 || this.decreaseInterval == 1)
Jaco geeft aan dat de PO dit wil.... Approved

2024-04-02 14:21 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagePriorityHandler.java
> +    if (this.decreaseEnabled && (retryCount > 0) && retryCount % this.decreaseInterval == 0) {
Jaco geeft aan dat de PO dit wil.... Approved

2024-04-02 14:32 UTC, merged