feature/SMHE-2066-Event-logs-in-Object-Configuration
OSGP/open-smart-grid-platform pull request #1269
Opened 2024-04-02 06:47 UTC by harrymiddelburgetall

2024-04-02 09:22 UTC, stefanermens requested changes

2024-04-02 09:22 UTC, stefanermens commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/bundle/BundledFindEvents.feature
> +      | DeviceModelCode      | MA105                  |
Are these settings necessary?

2024-04-02 09:22 UTC, stefanermens commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/bundle/BundledFindEvents.feature
> +      | TEST1024000000001    | DSMR     |   4.2.2 | 21 |  9 |  7 | 30 |  0 |   0 |  0 |
Do we need a test for DSMR2.2?

2024-04-02 09:22 UTC, stefanermens commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-dsmr422.json
> +      "group": "ELECTRICITY",
The event logs are group ABSTRACT, because they are not only related to electricity. This applies to all event logs and event codes, except the Mbus log en code. Those should be in group GAS.

2024-04-02 09:22 UTC, stefanermens commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-dsmr422.json
> +          "valuetype": "FIXED_IN_METER",
This value is fixed in profile. Also check this in other profiles.

2024-04-02 09:22 UTC, stefanermens commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-dsmr422.json
> +          "value": "CLOCK,2|COMMUNICATION_SESSION_EVENT_CODE,2|COMMUNICATION_SESSION_EVENT_COUNTER,0",
`COMMUNICATION_SESSION_EVENT_COUNTER,0` should be `COMMUNICATION_SESSION_EVENT_COUNTER,2`

2024-04-02 09:22 UTC, stefanermens commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-dsmr422.json
> +        }
I would prefer to list the 4 event counters seperately. This also avoids confusion with the `x` used in obis codes for channel.

2024-04-02 09:22 UTC, stefanermens commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/FindEventsCommandExecutor.java
> +    final DataObject clockDefinition = this.dlmsHelper.getClockDefinition();
Get this from object config as well

2024-04-02 09:22 UTC, stefanermens commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/FindEventsCommandExecutorTest.java
> +  void testSmr500Event(final EventLogCategoryDto eventLogCategoryDto)
Do we need a test for DSMR4.2.2 and DSMR2.2 as well?

2024-04-02 10:44 UTC, stefanermens commented on osgp/protocol-adapter-dlms/osgp-dlms/src/test/java/org/opensmartgridplatform/dlms/services/Protocol.java
> +  SMR_5_5("SMR", "5.5", 90, 11, 27, 6, 14, 6, 15, 10, 15, true, true);
Another object config related PR is merged, so check these numbers again.

2024-04-04 08:41 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/bundle/BundledFindEvents.feature
> +      | DeviceModelCode      | MA105                  |
No, I removed them

2024-04-04 08:51 UTC, harrymiddelburgetall commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-dsmr422.json
> +      "group": "ELECTRICITY",
Implemented ABSTRACT for all logs and event except MBUS

2024-04-04 08:56 UTC, harrymiddelburgetall commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-dsmr422.json
> +          "valuetype": "FIXED_IN_METER",
Implemented FIXED_IN_PROFILE for sort method attribute of all event logs

2024-04-04 08:57 UTC, harrymiddelburgetall commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-dsmr422.json
> +          "value": "CLOCK,2|COMMUNICATION_SESSION_EVENT_CODE,2|COMMUNICATION_SESSION_EVENT_COUNTER,0",
modified

2024-04-04 09:22 UTC, harrymiddelburgetall commented on osgp/protocol-adapter-dlms/osgp-dlms/src/main/resources/dlmsprofiles/dlmsprofile-dsmr422.json
> +        }
Obis code replaced with **0.0.96.15.4.255**

2024-04-04 09:51 UTC, harrymiddelburgetall commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/FindEventsCommandExecutor.java
> +    final DataObject clockDefinition = this.dlmsHelper.getClockDefinition();
Implemented with ObjectConfigServiceHelper

2024-04-04 10:20 UTC, harrymiddelburgetall commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/FindEventsCommandExecutorTest.java
> +  void testSmr500Event(final EventLogCategoryDto eventLogCategoryDto)
Added tests for DSMR 4.2.2 and DSMR 2.2

2024-04-04 12:39 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/bundle/BundledFindEvents.feature
> +      | TEST1024000000001    | DSMR     |   4.2.2 | 21 |  9 |  7 | 30 |  0 |   0 |  0 |
Added tests for DSMR 2.2

2024-04-04 14:19 UTC, stefanermens approved these changes

2024-04-04 16:09 UTC, merged