SMHE-1979 THD fingerprint and counters
OSGP/open-smart-grid-platform pull request #1281
Opened 2024-04-19 11:11 UTC by stefanermens

2024-04-30 06:45 UTC, harrymiddelburgetall commented
⏳ https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/239/

2024-04-30 14:18 UTC, wdevries97 commented
✔ https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/240/

2024-05-01 09:24 UTC, natasja-n requested changes

2024-05-01 09:24 UTC, natasja-n commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/ThdFingerprintSingleConverter.java
> +      return null;
zit niet in unit tests

2024-05-01 09:24 UTC, natasja-n commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/ThdFingerprintBundleConverter.java
> +      return null;
wordt niet in unit tests getest.

2024-05-01 09:24 UTC, natasja-n commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/GetThdFingerprintCommandExecutorTest.java
> +
wordt niet gebruikt

2024-05-01 09:24 UTC, natasja-n commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/GetThdFingerprintCommandExecutorTest.java
> +
wordt niet gebruikt

2024-05-01 09:24 UTC, natasja-n commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/GetThdFingerprintCommandExecutorTest.java
> +
wordt niet gebruikt

2024-05-01 09:25 UTC, natasja-n commented
Ik mis ook nog een description bij de pr.

2024-05-02 08:38 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/ThdFingerprintSingleConverter.java
> +      return null;
Added to test

2024-05-02 08:38 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/ThdFingerprintBundleConverter.java
> +      return null;
Added to test

2024-05-02 08:42 UTC, harrymiddelburgetall commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/GetThdFingerprintCommandExecutorTest.java
> +
removed

2024-05-02 08:42 UTC, harrymiddelburgetall commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/GetThdFingerprintCommandExecutorTest.java
> +
removed

2024-05-02 09:00 UTC, natasja-n approved these changes

2024-05-02 12:07 UTC, merged