SMHE-2011 Save firmware file to file system
OSGP/open-smart-grid-platform pull request #1324
Opened 2024-05-23 21:08 UTC by jboon

2024-05-28 06:22 UTC, harrymiddelburgetall commented
⏳ https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/249/

2024-05-28 10:01 UTC, stefanermens requested changes

2024-05-28 10:01 UTC, stefanermens commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/configuration/Firmware.feature
> +#    And a firmware
Can this block be removed?

2024-05-28 10:01 UTC, stefanermens commented on osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementService.java
> +   */
This block doesn't add any information. Can it be removed?

2024-05-28 10:01 UTC, stefanermens commented on osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementService.java
> +   */
I guess some `.` are missing?

2024-05-28 10:01 UTC, stefanermens commented on integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/glue/steps/ws/core/firmwaremanagement/FirmwareSteps.java
> +      // check is implicitly done in the tests using the file from file storage.
I don't understand this comment. Is the file on the filestorage used or not?

2024-05-28 10:01 UTC, stefanermens commented on integration-tests/cucumber-tests-platform-common/src/test/resources/features/common/osgp-adapter-ws-core/FirmwareManagement/AddOrChangeFirmware.feature
> +      |                  |                                          |              |          | without | without    |
Location is always FILE_STORAGE (or null). There is no test with location DATABASE. Can the DATABASE option be removed from the FirmwareSteps?

2024-05-28 10:01 UTC, stefanermens commented on integration-tests/cucumber-tests-platform-common/src/test/resources/features/common/osgp-adapter-ws-core/FirmwareManagement/AddOrChangeFirmware.feature
> +      | FirmwareHashType           | <hashtype>                                           |
Only hashtype SHA256 is tested. Should there be a test for MD5 a well?

2024-05-28 10:01 UTC, stefanermens commented on osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementService.java
>    private FirmwareFile insertOrUdateDatabase(
`Update` instead of `Udate`

2024-05-28 10:01 UTC, stefanermens commented on osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareFileStorageServiceTest.java
> +
Do we need a test when the firmware file is null or empty?

2024-05-28 10:01 UTC, stefanermens commented on osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementServiceTest.java
> +    // Only testing the file storage solution
Is there another solution?

2024-05-28 10:01 UTC, stefanermens commented on osgp/platform/osgp-core/src/test/java/org/opensmartgridplatform/core/infra/jms/protocol/inbound/messageprocessors/GetFirmwareFileMessageProcessorTest.java
> +            new UpdateFirmwareRequestDataDto(firmwareFileIdentification, null, null));
Should we test hashtype and digest as well?

2024-05-28 14:40 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/configuration/Firmware.feature
> +#    And a firmware
Yes, removed

2024-05-29 07:13 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/glue/steps/ws/core/firmwaremanagement/FirmwareSteps.java
> +      // check is implicitly done in the tests using the file from file storage.
Elaborated the comment a bit more

2024-05-29 07:15 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-common/src/test/resources/features/common/osgp-adapter-ws-core/FirmwareManagement/AddOrChangeFirmware.feature
> +      |                  |                                          |              |          | without | without    |
Commented in the feature file on why only FILE_STORAGE and SHA256 is tested.

2024-05-29 07:16 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-common/src/test/resources/features/common/osgp-adapter-ws-core/FirmwareManagement/AddOrChangeFirmware.feature
> +      | FirmwareHashType           | <hashtype>                                           |
Commented in the feature file on why only FILE_STORAGE and SHA256 is tested.

2024-05-29 07:18 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementService.java
>    private FirmwareFile insertOrUdateDatabase(
Corrected typo

2024-05-29 07:21 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementService.java
> +   */
Removed

2024-05-29 07:25 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementService.java
> +   */
Additional Sentence ending (.) and starting with capital clarifies the text

2024-05-29 07:39 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareFileStorageServiceTest.java
> +
Added checks

2024-05-29 07:43 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementServiceTest.java
> +    // Only testing the file storage solution
SmartMetering application use the file storage solution. Other applications might use Database storage which is not covered by this test yet. Comment clarified.

2024-05-29 08:00 UTC, harrymiddelburgetall commented on osgp/platform/osgp-core/src/test/java/org/opensmartgridplatform/core/infra/jms/protocol/inbound/messageprocessors/GetFirmwareFileMessageProcessorTest.java
> +            new UpdateFirmwareRequestDataDto(firmwareFileIdentification, null, null));
The class GetFirmwareFileMessageProcessor tested here is not doing anything with these parameters. For completeness added to the test

2024-05-30 08:21 UTC, stefanermens approved these changes

2024-05-30 10:15 UTC, merged