Solving SonarQube issues
OSGP/open-smart-grid-platform pull request #446
Opened 2020-10-06 07:29 UTC by mvanOsch

2020-10-08 12:13 UTC, MithraicMagic approved these changes
Looks good!

2020-10-20 08:55 UTC, robindenadel requested changes
IDE settings for formatting and save actions are not OK.
See https://documentation.opensmartgridplatform.org/Opensourcecommunity/ToolsguidelinesCI.html

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java
> +                    new ValidationException(e.getConstraintViolations())));
see DeviceManagementEndpoint

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java
> +    @SuppressWarnings("squid:S3457")
Explanation is missing.

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java
> +    @SuppressWarnings("squid:S3457")
Explanation is missing

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java
> +    @SuppressWarnings("squid:S3457")
Explanation is missing

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java
> +    @SuppressWarnings("squid:S3457")
Explanation is missing

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java
> +    @SuppressWarnings("squid:S3457")
Explanation is missing

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-tariffswitching/src/main/java/org/opensmartgridplatform/adapter/ws/tariffswitching/endpoints/TariffSwitchingAdHocManagementEndpoint.java
> +                    new ValidationException(e.getConstraintViolations())));
see DeviceManagementEndpoint

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-tariffswitching/src/main/java/org/opensmartgridplatform/adapter/ws/tariffswitching/endpoints/TariffSwitchingScheduleManagementEndpoint.java
> +                    new ValidationException(e.getConstraintViolations())));
see DeviceManagementEndpoint

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/Ssld.java
> +    @SuppressWarnings("squid:S2159")
Explanation is missing

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/exceptions/ValidationException.java
> +@SuppressWarnings("squid:S1452")
I don't consider this a good explanation.

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/AbstractPushSetup.java
> +    @SuppressWarnings("squid:S1168")
I don't think we should suppress this warning, and return an empty list.
Write unit tests for all the code calling this method to make sure everything keeps on working ok.

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/AbstractPushSetup.java
> +    @SuppressWarnings("squid:S1168")
I don't think we should suppress this warning, and return an empty list.
Write unit tests for all the code calling this method to make sure everything keeps on working ok.

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/ClockStatus.java
> +    @SuppressWarnings("squid:S1168")
I don't think we should suppress this warning, and return an empty set.
Write unit tests for all the code calling this method to make sure everything keeps on working ok.

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/ClockStatusBit.java
> +    @SuppressWarnings("squid:S1168")
I don't think we should suppress this warning, and return an empty set.
Write unit tests for all the code calling this method to make sure everything keeps on working ok.

2020-10-20 08:55 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/SpecificAttributeValueRequest.java
> +    @SuppressWarnings("squid:S2159")
Don't suppress this warning

2020-10-20 08:55 UTC, robindenadel commented on osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/services/commands/Iec61850GetConfigurationCommand.java
> +@SuppressWarnings("DuplicatedCode")
Don't suppress this warning

2021-01-07 12:15 UTC, mvanOsch commented
retest this please

2021-01-14 08:45 UTC, mvanOsch commented
retest this please

2021-01-14 09:24 UTC, mvanOsch commented
retest this please

2021-01-14 15:08 UTC, robindenadel requested changes

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/services/DeviceManagementServiceTest.java
> +        Assertions.assertThat(resultPage).isNull();
use a static import so we don't need to put Assertions. here

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/services/DeviceManagementServiceTest.java
> +        });
refactor the return part into a method

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/services/DeviceManagementServiceTest.java
> +class DeviceManagementServiceTest {
there are only tests checking for the resultPage to be null
I would expect tests checking a non-null result as well

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/services/DeviceManagementServiceTest.java
> +        });
see earlier comment

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java
> -
the empty line was fine here, roll back the change

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/exceptions/ValidationException.java
> +
why was the order of methods changed?

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/ClockStatus.java
> +            return new HashSet<ClockStatusBit>();
this line introduced another sonar issue

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/ClockStatusBit.java
> -    DAYLIGHT_SAVING_ACTIVE("daylight saving active");
why was the order of elements changed?

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/ClockStatusBit.java
> -    }
why was the order of methods changed?

2021-01-14 15:08 UTC, robindenadel commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/ClockStatusBit.java
> +    // shouldn't be suppressed.
very good!

2021-01-14 15:49 UTC, MithraicMagic requested changes

2021-01-14 15:49 UTC, MithraicMagic commented on osgp/platform/osgp-adapter-domain-smartmetering/src/test/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/mapping/customconverters/PushSetupAlarmDtoConverterTest.java
> +    private PushSetupAlarmDto pushSetupAlarmDto;
Mock is not used in class. Maybe remove?

2021-01-14 15:49 UTC, MithraicMagic commented on osgp/platform/osgp-adapter-domain-smartmetering/src/test/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/mapping/customconverters/PushSetupAlarmDtoConverterTest.java
> +        this.pushSetupAlarmDtoConverter = new PushSetupAlarmDtoConverter(this.configurationMapper);
This is used in both functions, set globally in class?

2021-01-19 15:46 UTC, MithraicMagic approved these changes
Looks good!

2021-01-21 07:46 UTC, robindenadel requested changes

2021-01-21 07:46 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-smartmetering/src/test/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/mapping/customconverters/PushSetupAlarmDtoConverterTest.java
> + * Copyright 2020 Alliander N.V.
2021

2021-01-21 07:46 UTC, robindenadel commented on osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/services/DeviceManagementServiceTest.java
> + * Copyright 2020 Alliander N.V.
2021

2021-01-21 08:43 UTC, mvanOsch commented
retest this please

2021-01-21 09:15 UTC, robindenadel approved these changes

2021-01-21 09:46 UTC, merged