increased test coverage of scheduleManagementService
OSGP/open-smart-grid-platform pull request #463
Opened 2020-10-15 09:06 UTC by Thijnvdb

2020-10-15 09:12 UTC, MithraicMagic requested changes
Just some very minor things, rest looks good!

2020-10-15 09:12 UTC, MithraicMagic commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +@MockitoSettings(strictness = Strictness.LENIENT)
Can be removed, standard strictness should be good.

2020-10-15 09:12 UTC, MithraicMagic commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +    private OsgpCoreRequestMessageSender osgpCoreRequestMessageSender;
Indentation is a bit sketchy on this line

2020-10-15 09:12 UTC, MithraicMagic commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +		final int priority = 1;
Maybe introduce these as constants in the class, since they are also used (and tested) in testSetTariffScheduleFunctionalExceptionThrown()

2020-10-15 09:24 UTC, MithraicMagic approved these changes
Looks good!

2020-11-13 08:32 UTC, robindenadel requested changes

2020-11-13 08:32 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +	private final long scheduleTime = (long) 0.0f;
no need to cast, just use 0L.

2020-11-13 08:32 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +package org.opensmartgridplatform.adapter.domain.tariffswitching.application.services;
Formatting is not ok, check your Eclipse settings.

2020-11-13 08:32 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +		final DeviceOutputSetting dos = Mockito.mock(DeviceOutputSetting.class);
don't use abbreviations in naming, here use deviceOutputSetting

2020-11-13 08:32 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +	public void setup() throws FunctionalException {
method should be private
a method called setup in a test class is usually annotated with BeforeEach
in this test class, the method is only called from one test method, so the name is a bit confusing.
I would name it arrangeSetTariffScheduleTest and insert it after testSetTariffSchedule

2020-11-13 08:32 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +		when(this.device.getId()).thenReturn((long) 0.0f);
0L

2020-11-13 08:32 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +		when(this.device.getDeviceType()).thenReturn(Ssld.SSLD_TYPE);
Why is this not part of the setup?

2020-11-13 08:32 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +		final ArgumentCaptor<Integer> priorityCapture = ArgumentCaptor.forClass(int.class);
I would prefer a Captor annotation, see SubscriptionServiceTest for example.

2020-11-13 08:32 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +		assertThatThrownBy(()-> this.scheduleManagementService.setTariffSchedule(this.correlationIds, this.scheduleEntries,
when using assertThatExceptionOfType(<Exception.>class).isThrownBy(() -> 
we check the type of exception as well

2020-12-10 07:38 UTC, robindenadel requested changes

2020-12-10 07:38 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> + * Copyright 2015 Smart Society Services B.V.
2020 Alliander

2020-12-10 07:38 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +package org.opensmartgridplatform.adapter.domain.tariffswitching.application.services;
still not ok

2020-12-10 07:38 UTC, robindenadel commented on osgp/platform/osgp-adapter-domain-tariffswitching/src/test/java/org/opensmartgridplatform/adapter/domain/tariffswitching/application/services/ScheduleManagementServiceTest.java
> +		//idk how many entries are typically required
comment is not clear to me, what does it mean?

2020-12-10 10:09 UTC, Thijnvdb commented
retest this please

2021-09-23 09:11 UTC, closed without merging