FLEX-5580: Adds location information to the kafka message.
OSGP/open-smart-grid-platform pull request #493
Opened 2020-11-05 16:20 UTC by robindenadel

2020-11-06 15:28 UTC, bvdzwet requested changes

2020-11-09 07:54 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/LowVoltageMeasurementType.java
> + * Copyright 2020 Smart Society Services B.V.
changed it

2020-11-09 08:02 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/LowVoltageMeasurementType.java
> +    CURRENT_HARMONIC_L1_H3(20, "I1-H3", UnitSymbol.A),
replaced L with I

2020-11-09 08:03 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/LowVoltageMetaMeasurementToAnalogList.java
> + * Copyright 2020 Smart Society Services B.V.
file was deleted

2020-11-09 08:23 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/LowVoltageMetaMeasurementType.java
> + * Copyright 2020 Smart Society Services B.V.
changed it

2020-11-09 08:24 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/ScadaMeasurementPublishedEventConverter.java
> +        if (source == null || source.getData() == null) {
included extra check

2020-11-09 08:25 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/ScadaMeasurementPublishedEventConverter.java
> +                    LowVoltageMeasurementType.getNumberOfElements(), measurementValues.length, source);
you already done that :)

2020-11-09 08:26 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/ScadaMeasurementPublishedEventConverter.java
> +                this.createPowerSystemResource(source), source.getCreatedUtcSeconds() * 1000l,
you already done that :)

2020-11-09 08:31 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/infra/kafka/out/ScadaMeasurementPublishedEventProducer.java
> +            if (payloads.length == 0 || payloads[0] == null) {
added a comment and log line

2020-11-09 08:33 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/infra/kafka/out/ScadaMeasurementPublishedEventProducer.java
> +            if (Integer.valueOf(feeder) != 100) {
refactored it into a constant META_MEASUREMENT_FEEDER

2020-11-09 08:33 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/resources/location-info.properties
> +9005762.location=Balkon Zuid
you are correct, it was about this file

2020-11-09 08:34 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/test/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/LsPeakShavingMessageFactory.java
>  public class LsPeakShavingMessageFactory extends MessageFactory {
done so

2020-11-09 08:35 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/test/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/ScadaMeasurementPublishedEventConverterTest.java
> +        assertThat(event.getCreatedDateTime()).isEqualTo(utcSeconds * 1000l);
done so

2020-11-09 08:36 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/test/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/ScadaMeasurementPublishedEventConverterTest.java
> +    void testSomeOtherPayload() {
changed it

2020-11-09 08:37 UTC, robindenadel commented on osgp/platform/osgp-adapter-kafka-distributionautomation/src/test/java/org/opensmartgridplatform/adapter/kafka/da/infra/kafka/out/ScadaMeasurementPublishedEventProducerTest.java
> +    private LocationConfig locationconfig;
changed it

2020-11-09 16:40 UTC, kevinsmeets commented
retest this please

2020-11-10 09:18 UTC, merged