Slim 2859 correlation uid secret mgmt
OSGP/open-smart-grid-platform pull request #587
Opened 2021-03-17 20:57 UTC by jandik

The general goal was to add the correlation UID to all messages and logging to/from secret mgmt. In order to facilitate this a lot of plumbing had to be done to get the correlation UID along the following route: JMS message -> protocol-adapter -> soap -> secret mgmt.
- Add datastructures for propagating metadata/correlation UID (RequestWithMetadata, CorrelatedObject)
- Refactored message processors (plumbing and added generics to simplify and generalise code)
- Modified WSDL (added correlationUID and added base request/response)
- Refactored secret management endpoint (added correlation UID & used functional interface to process all requests in 1 general way)

2021-03-18 10:14 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/threads/RecoverKeyProcess.java
> +        LOGGER.info("[{}] Attempting key recovery for device {}", this.correlationUid, this.deviceIdentification);
I see you use Lombok, might as well add @Slf4j

2021-03-18 10:16 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/wsclient/SecretManagementClient.java
> +                        .format("<%1$s xmlns=\"%2$s\">%3$s</%1$s>", CORRELATION_UID, NAMESPACE_URI, correlationUid);
didn't know this feature, you can number the placeholders, nice to know

2021-03-18 10:21 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/CorrelatedObject.java
> +public class CorrelatedObject<T> implements ActionRequestDto {
I find this a bit generic since it adapts ActionRequestDto. Personally I would choose CorrelatedActionRequestDto

2021-03-18 10:27 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/CorrelatedObject.java
> +public class CorrelatedObject<T> implements ActionRequestDto {
Maybe even remove the interface ActionRequestDto from CorrelatedObject, extend CorrelatedObject as CorrelatedActionRequest and put the interface on CorrelatedActionRequest. This makes CorrelatedObject usable in other situation where you need a Correlated Object.

2021-03-18 10:30 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/security/GenerateAndReplaceKeyCommandExecutor.java
> +            final CorrelatedObject<ActionRequestDto> actionRequestDto) throws OsgpException {
I must admit though that it probably is easier to read: CorrelatedObject vs CorrelatedActionRequestDto

2021-03-18 10:32 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/security/ReplaceKeyCommandExecutor.java
> -
+1

2021-03-18 10:32 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/security/ReplaceKeyCommandExecutor.java
> +        return ReplaceKeyInput.from(bytes, keyId, securityKeyType, isGenerated);
+1

2021-03-18 10:41 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/DeviceRequestMessageProcessor.java
> +            if (this.requiresExistingDevice()) {
+1

2021-03-18 10:42 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/processors/AddMeterRequestMessageProcessor.java
> +        return false;
+1

2021-03-18 10:45 UTC, jboon commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/processors/UpdateFirmwareRequestMessageProcessor.java
> +            final RequestWithMetadata<String> request) throws OsgpException {
holy moly, +1

2021-03-18 10:46 UTC, jboon approved these changes

2021-03-18 10:56 UTC, jboon commented on osgp/platform/osgp-secret-management/src/main/java/org/opensmartgridplatform/secretmanagement/application/endpoints/SecretManagementEndpoint.java
> +            final Transformer transformer = transformerFactory.newTransformer();
see https://rules.sonarsource.com/java/tag/owasp/RSPEC-2755

add
transformerFactory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
transformerFactory.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET, "");

2021-03-18 11:03 UTC, jboon requested changes
see comment for blocking sonar issue

2021-03-18 11:26 UTC, harrymiddelburgetall approved these changes
Nice work. Good attempt on the (formatting) conventions. Mind to keep method documentation up-to-date

2021-03-30 14:01 UTC, closed without merging

2021-03-30 14:02 UTC, jandik commented
Rework done, opening fresh PR for GXF review