SLIM-3065 Add auxiliary events
OSGP/open-smart-grid-platform pull request #697
Opened 2021-08-13 13:54 UTC by stefanermens

Signed-off-by: stefanermens <stefan.ermens@alliander.com>

2021-08-30 07:44 UTC, stefanermens commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/dlmsobjectconfig/DlmsObjectConfigDsmr422.java
> +        Arrays.asList(standardEventLogCode, fraudDetectionEventLogCode, mbusEventLogCode));
The Communication Sessions Log is not included in DSMR4. It was added in SMR5.

2021-08-30 08:27 UTC, kroesctrl commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringbundle/BundledFindEventsSteps.java
> +    assertThat(findEventsResponse.getEvents().size()).isEqualTo(nrOfEvents);
Changed

2021-08-30 08:27 UTC, kroesctrl commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmanagement/FindAuxillaryEventsReads.java
> + * Copyright 2021 Alliander N.V.
Changed

2021-08-30 08:28 UTC, kroesctrl commented on osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/ManagementService.java
> +            .withResult(resultType)
Indeed

2021-08-30 08:29 UTC, kroesctrl commented on osgp/platform/osgp-adapter-domain-smartmetering/src/test/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/EventServiceTest.java
>    private void assertEventType(
Agree

2021-08-30 08:34 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/mapping/DataObjectToEventListConverter.java
>      return eventData.get(1).getValue();
Yes, it is done because Auxiliary has integer and older have Short values.
Requested change made

2021-08-30 08:35 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/FindEventsCommandExecutorTest.java
> +              final DataObject eventCode = DataObject.newUInteger16Data((int) code);
Changed

2021-08-30 09:05 UTC, kroesctrl approved these changes

2021-08-31 07:16 UTC, bvdzwet commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/dlmsobjectconfig/DlmsObjectConfigDsmr422.java
> +        Arrays.asList(standardEventLogCode, fraudDetectionEventLogCode, mbusEventLogCode));
What did you base the reply that the Communication Session Log was added in SMR5 on?
My question why it was not included was based on the Dutch Smart Meter Requirements v4.2.2 P3 Companion Standard, where the Communication Session Log is mentioned in the table of section 4.2.1 Events, below this table with code "0-0:96-11.4.255" and in 4.2.2 Event Logs with code "0-0:99.98.4.255", with a more detailed description of the capture objects in section 5.10 Communication Sessions (event log).

2021-08-31 09:18 UTC, stefanermens commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/dlmsobjectconfig/DlmsObjectConfigDsmr422.java
> +        Arrays.asList(standardEventLogCode, fraudDetectionEventLogCode, mbusEventLogCode));
You're right, the Communication Session Log was already in the final version DSMR4.2.2. I've added the log to the config.

2021-08-31 10:24 UTC, harrymiddelburgetall approved these changes

2021-08-31 12:15 UTC, bvdzwet requested changes

2021-08-31 12:16 UTC, kroesctrl commented on osgp/platform/osgp-adapter-domain-smartmetering/pom.xml
> +      <version>5.5.2</version>
Changed

2021-08-31 12:22 UTC, bvdzwet approved these changes

2021-08-31 13:23 UTC, merged