Fixed 2 connection issues in the protocol adapter.
OSGP/open-smart-grid-platform pull request #739
Opened 2021-11-09 21:01 UTC by kroesctrl

2021-11-10 08:05 UTC, carlogeenen commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/DlmsConnectionManagerTest.java
> +    this.manager.close();
Please verify the absence of a connection by:
this.manager.isConnected(); 
before calling .close()

2021-11-10 14:38 UTC, bvdzwet reviewed
If I remember correctly, having the deviceRepository in the InvocationCounterManager to save the device in the past lead to exception stack traces in the logs.
If someone can confirm the code works on an actual device with an out of sync invocation counter, without avoidable exceptions, the changes look OK (at least for now).

I am a bit worried about existing code in `org.opensmartgridplatform.adapter.protocol.dlms.infra.messaging.DeviceRequestMessageProcessor.processMessageTasks(Serializable, MessageMetadata, DlmsConnectionManager)` (lines 149..152):
```java
    // ...
    } finally {
      final DlmsDevice device = this.domainHelperService.findDlmsDevice(messageMetadata);
      this.doConnectionPostProcessing(device, connectionManager, messageMetadata);
    }
    // ...
```
If this was only done because the device variable is not in scope in the finally block, this had better been solved by moving the declaration and null-initialization of the device to before opening of the try block.
The method `findDlmsDevice(MessageMetadata)` has side effects for devices that do not have a static IP address, The session provider may be asked for an IP address for a session with the device by its IccId. This is something that helps at the start of setting a connection, but I think it may harm when called before closing the connection.
If removal of this findDlmsDeviceMethod from the finally block works as well, I think it may be a nicer solution than putting the deviceRepository in the InvocationCounterManager. If the latter works without exceptions in the logs I think it is an OK enough solution though.

2021-11-11 13:44 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/services/DomainHelperService.java
> +    this.dlmsDeviceRepository.save(dlmsDevice);
I would like to move the update of the ip-address to a separate method.........

2021-11-11 13:44 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/DlmsConnectionHelper.java
> +        return;
Without this return always a exeception is thrown when a invocation counter is out-of-sync

2021-11-11 16:25 UTC, bvdzwet requested changes
Most of the code looks like good to necessary improvements.
If my worries about the change in the `RecoverKeyProcess` regarding whether the message metadata always holds the IP address that is also in the instance field are taken away I have no further doubts.

2021-11-11 16:27 UTC, bvdzwet commented
retest this please

2021-11-12 07:17 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/threads/RecoverKeyProcess.java
> +      return this.domainHelperService.findDlmsDevice(this.messageMetadata);
I totally agree, i revert the changes on the RecoverKeyProcess and added the two argument method

2021-11-12 07:52 UTC, bvdzwet approved these changes

2021-11-12 08:13 UTC, merged