Make sure logicalId is unique in test suite
OSGP/open-smart-grid-platform pull request #871
Opened 2022-07-07 10:21 UTC by kroesctrl

Signed-off-by: Gerben Kroes <gerben@kroesctrl.nl>

2022-07-07 11:50 UTC, harrymiddelburgetall requested changes
Congratulations! Nice improvement of the tests with simulators. Just a few remarks.

2022-07-07 11:50 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/SimulatorDeviceRegister.java
> +  private final HashMap<Long, Map<String, Long>> logicalIdByPortByDeviceIdentification =
private final **Map**<Long, Map<String, Long>> logicalIdByPortByDeviceIdentification =
      new HashMap<>();

2022-07-08 06:17 UTC, kroesctrl commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/SimulatorDeviceRegister.java
> +    final Long newLogicalId = lastLogicalId.orElse(0L) + 1;
The last logicalId should be calculated by port

2022-07-08 06:18 UTC, kroesctrl commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/SimulatorDeviceRegister.java
> +  private final HashMap<Long, Map<String, Long>> logicalIdByPortByDeviceIdentification =
Chcek, aangepast

2022-07-08 06:20 UTC, kroesctrl commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/DlmsDeviceSteps.java
> +    this.setLogicalDeviceId(dlmsDevice);
Refactored

2022-07-08 06:21 UTC, kroesctrl commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/DlmsDeviceSteps.java
> +    this.dlmsDeviceRepository.save(dlmsDevice);
Changed

2022-07-11 05:11 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/SimulatorDeviceRegister.java
> +    final Long newLogicalId = lastLogicalId.orElse(0L) + 1;
true

2022-07-11 05:12 UTC, harrymiddelburgetall approved these changes

2022-07-11 06:50 UTC, kroesctrl commented
https://ci.opensmartgridplatform.org/job/OSGP_open-smart-grid-platform_pr/3186/

2022-07-11 07:24 UTC, kroesctrl commented
Retest this please

2022-07-11 07:25 UTC, merged