Feature/fdp 623
OSGP/open-smart-grid-platform pull request #885
Opened 2022-09-05 09:21 UTC by jasperkamerling

2022-09-07 09:45 UTC, JelleHoffman requested changes, later dismissed

2022-09-07 09:45 UTC, JelleHoffman commented on integration-tests/cucumber-tests-platform-publiclighting/src/test/resources/features/publiclighting/osgp-adapter-ws-publiclighting/ScheduleManagement/SetLightSchedule.feature
> +@PublicLighting @Platform @PublicLightingSetLightSchedule @Jasper
Development code?

2022-09-07 09:47 UTC, jasperkamerling commented on integration-tests/cucumber-tests-platform-publiclighting/src/test/resources/features/publiclighting/osgp-adapter-ws-publiclighting/ScheduleManagement/SetLightSchedule.feature
> +@PublicLighting @Platform @PublicLightingSetLightSchedule @Jasper
oops, is nu weer weg

2022-09-07 10:39 UTC, smvdheijden requested changes
- Looks like this pull request contains several formatting changes in the feature files. Check if you could keep numbers right-aligned. In Eclipse this could be set in the preferences, not sure about IntelliJ.
- You've added some additional examples to the SetLightSchedule feature, but shouldn't there be any additional examples in the GetLightStatus feature as well?

2022-09-07 10:39 UTC, smvdheijden commented on osgp/platform/osgp-adapter-ws-publiclighting/src/main/java/org/opensmartgridplatform/adapter/ws/publiclighting/application/mapping/converters/LightValueConverter.java
> + * Copyright 2021 Alliander N.V.
```suggestion
 * Copyright 2022 Alliander N.V.
```

2022-09-07 10:39 UTC, smvdheijden commented on osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/application/mapping/LightValueToOslpLightValueMapper.java
>      if (source.hasDimValue()) {
```suggestion
    if (source.hasDimValue() && source.hasOn()) {
```

2022-09-07 11:41 UTC, jasperkamerling commented
Intellij doesnt have a different alignment for numbers. But the eclipse allignement also doesn't really work because most of the numbers here are actually lists of numbers so those would need to go on the left.
I'll change them back for now but maybe we can look into it later and fix this in Eclipse.

2022-09-14 12:19 UTC, smvdheijden requested changes

2022-09-14 12:19 UTC, smvdheijden commented on osgp/shared/pom.xml
> +        <module>osgp-ws-secret-management</module>
osgp-ws-secret-management should not be needed here.

2022-09-14 12:56 UTC, smvdheijden approved these changes

2022-09-14 12:58 UTC, smvdheijden approved these changes

2022-09-14 15:55 UTC, merged