SMHE-983 KPI verbetering: validation error meldingen op verzoeken 401
OSGP/open-smart-grid-platform pull request #890
Opened 2022-09-08 08:39 UTC by natasjaalliander

log exception and continue with creating bundle list in ActionMapperService

2022-09-08 08:48 UTC, kroesctrl requested changes

2022-09-08 08:48 UTC, kroesctrl commented on osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/ActionMapperService.java
> +        actionValueObjectDtoList.add(this.mapActionWithMapper(smartMeter, action));
Ik verwacht niet dat dit goed genoeg is. Er moeten evenveel responses zijn als dat er actions zijn. 
Lijkt me dat er wel een error response toegevoegd moet worden

2022-09-22 07:31 UTC, kroesctrl commented
https://jenkins.fdp.osgp.cloud/view/Nightly%20Build/job/gxf-nightly-build/497/

2022-09-22 13:12 UTC, kroesctrl approved these changes

2022-09-22 13:15 UTC, natasjaalliander reviewed
approved by Natasja

2022-09-23 10:04 UTC, kroesctrl commented
https://jenkins.fdp.osgp.cloud/view/Nightly%20Build/job/gxf-nightly-build/502/

2022-09-23 13:21 UTC, merged