Feature/kpn session enddate
OSGP/open-smart-grid-platform pull request #926
Opened 2022-10-13 13:59 UTC by harrymiddelburgetall

The GetSessionInfo request functionally differ between REST and SOAP interfaces of JasperWireless
- REST-interface returns information about the current **or most recent data session** for a given device.
- SOAP-interface returns the current session information (IP address and session start time) for one or more devices. If the specified device is **not in session, no information** is returned.

Furthermore the SensSmsResponse of the REST interface returns in contradiction to the documentation a  **_smsMessageId_** insteadof a **_smsMsgId_**

2022-10-13 14:00 UTC, harrymiddelburgetall commented
Nightly: https://jenkins.fdp.osgp.cloud/view/Nightly%20Build/job/gxf-nightly-build/535/

2022-10-13 14:39 UTC, kroesctrl requested changes

2022-10-13 14:39 UTC, kroesctrl commented on osgp/protocol-adapter-dlms/osgp-jasper-interface/src/main/java/org/opensmartgridplatform/adapter/protocol/jasper/rest/client/JasperWirelessTerminalRestClient.java
> +
Now the same variable is used twice, would it not be nice to make a method:
sessionInfoResponse = getValidSessionInfoResponse(getSessionInfoResponseEntity)

2022-10-13 14:51 UTC, harrymiddelburgetall commented on osgp/protocol-adapter-dlms/osgp-jasper-interface/src/main/java/org/opensmartgridplatform/adapter/protocol/jasper/rest/client/JasperWirelessTerminalRestClient.java
> +
I agree

2022-10-13 14:54 UTC, harrymiddelburgetall commented
Nightly: https://jenkins.fdp.osgp.cloud/view/Nightly%20Build/job/gxf-nightly-build/536/

2022-10-13 15:47 UTC, kroesctrl approved these changes

2022-10-14 04:53 UTC, kroesctrl approved these changes

2022-10-17 09:30 UTC, merged