Feature/smhe 1193 no protocol info ref for gmeters
OSGP/open-smart-grid-platform pull request #960
Opened 2022-12-09 16:23 UTC by abolder

No communication method for G-Meter devices
Device field communication method is nullable.

2022-12-12 14:59 UTC, harrymiddelburgetall requested changes
I think with this PR you introduce the mismatch of information (ProtocolVariant)

2022-12-12 14:59 UTC, harrymiddelburgetall commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/installation/AddSmartMeter.feature
> +  @NightlyBuildOnly @Skip
Why is this newly added test skipped?

2022-12-12 14:59 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/SmartMeterService.java
> +    }
You assume here that if the protocolInfo with a variant is not found that the variant is not relevant and can be substituted with another randomly picked variant from the list of available variants. This might be the case in your story but possibly introduces incorrect information in others.

2022-12-13 00:48 UTC, kroesctrl approved these changes

2022-12-13 00:48 UTC, kroesctrl commented on integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/installation/AddSmartMeter.feature
> +  @NightlyBuildOnly @Skip
Both annotations are removed

2022-12-13 00:48 UTC, kroesctrl commented on osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/SmartMeterService.java
> +    }
You're right i will change it

2022-12-13 00:53 UTC, kroesctrl commented
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/18/

2022-12-13 07:23 UTC, harrymiddelburgetall commented on osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/SmartMeterService.java
> +    }
Better.

2022-12-13 07:24 UTC, harrymiddelburgetall approved these changes

2022-12-13 08:41 UTC, merged