Move output setting to device table
OSGP/open-smart-grid-platform pull request #974
Opened 2023-01-30 08:33 UTC by jasperkamerling

The database doesn't match the JPA model that was created. This may cause issues when deleting ssld's or devices.
The real solution would be to refactor the database but this is a first step to have the jpa model match the database.

![Schema](https://user-images.githubusercontent.com/15668493/215426490-c1079275-a35a-4cbb-bbe5-d56abf25c21b.png)

2023-01-30 09:12 UTC, smvdheijden requested changes

2023-01-30 09:12 UTC, smvdheijden commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/Device.java
> +
I prefer not to have an SSLD specific field in the generic device Entitiy. It would probably be better to change the relationship in the DB and change the foreign key to point to the ssld id (which should effectively be the same as the device id due to the inheritance relation between them)?

2023-01-30 09:24 UTC, jasperkamerling commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/Device.java
> +
True that would be better but that would be a big change in the data model.
This just fixes the application issues with the data model.

2023-01-31 09:25 UTC, smvdheijden commented on osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/Device.java
> +
I don't think a big change in the data model is needed. Setting ON DELETE CASCADE will probably also work?

2025-09-08 14:10 UTC, closed without merging