Make use of Artemis jms client library possible
OSGP/open-smart-grid-platform pull request #977
Opened 2023-01-31 12:28 UTC by kroesctrl

Signed-off-by: Gerben Kroes <gerben@kroesctrl.nl>

2023-01-31 12:30 UTC, kroesctrl commented
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/32/

2023-01-31 13:08 UTC, kroesctrl commented
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/33/

2023-02-01 08:19 UTC, abolder approved these changes

2023-02-01 10:45 UTC, kroesctrl commented
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/34/

2023-02-01 12:26 UTC, jasperkamerling commented on osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/JmsBrokerArtemis.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(JmsBrokerActiveMq.class);
The logger does not match the class

2023-02-01 12:26 UTC, jasperkamerling commented on osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/JmsBrokerActiveMq.java
> +    this.redeliveryPolicy = this.getRedeliveryPolicy();
I don't really think we need a field for this function. And using an overridable method in a constructor is discouraged.

2023-02-01 12:27 UTC, jasperkamerling commented
I'm also missing some unit tests on the new configuration code

2023-02-02 04:16 UTC, kroesctrl reviewed
Unit tests are added

2023-02-02 04:16 UTC, kroesctrl commented on osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/JmsBrokerArtemis.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(JmsBrokerActiveMq.class);
Changed

2023-02-02 04:16 UTC, kroesctrl commented on osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/JmsBrokerActiveMq.java
> +    this.redeliveryPolicy = this.getRedeliveryPolicy();
Agree, changed

2023-02-02 07:56 UTC, jasperkamerling requested changes

2023-02-02 07:56 UTC, jasperkamerling commented on osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/JmsPropertyNames.java
> +  public static String PROPERTY_NAME_CONNECTION_QUEUE_CONSUMER_WINDOW_SIZE =
Should be final

2023-02-02 08:36 UTC, kroesctrl commented on osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/JmsPropertyNames.java
> +  public static String PROPERTY_NAME_CONNECTION_QUEUE_CONSUMER_WINDOW_SIZE =
aangepast

2023-02-02 08:38 UTC, jasperkamerling approved these changes

2023-02-06 14:51 UTC, merged